stock:
  token: pnYuBlqq1W8G2gLdzFasEl6voDy3yfd22PzHjKvd
  url:
    quote: https://api.stockdata.org/v1/data/quote?symbols=%s&api_token=%s
    historical-quote: https://api.stockdata.org/v1/data/eod/multiple?symbols=%s&date=%s&api_token=%s
server:
  port:8010