stock:
  token: pnYuBlqq1W8G2gLdzFasEl6voDy3yfd22PzHjKvd
  url:
    quote: https://api.stockdata.org/v1/data/quote?symbols=%s&api_token=%s
    historical-quote: https://api.stockdata.org/v1/data/eod/multiple?symbols=%s&date=%s&api_token=%s
server:
  port: 8010

auth:
  audience: stock-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-dnqy-t57.eu.auth0.com/